### ISSUE TITLE
I am not authorized to view the video by pasting the link.

### ISSUE THREAD

**Issue by TruePhad** [ambr0sial/fuckyoutube#2]
Hello, I have a problem that I do not know if it will only happen to me or I have to do something to proceed, but the thing is that once I do the whole process and paste the link in my browser, I get the following:
Access has been denied to rr3---sn-sn-ja5gvjv-hqxs.googlevideo.com You are not authorized to view this page.
HTTP ERROR 403

Is there any way to have such "authorization"?
I am using the command: python fuckyoutube_pure.py

**Comment by Cadehlinha** [comment]
Hi, this behavior is because the creator did not parse the raw escape sequences created in the pure link generation, and trying to use the generated link will not lead to the video URL, but instead the mother domain which gives restricted access. I've created a fork of the repository [here](https://github.com/Cadehlinha/fuckyoutube) that fixes the issue (as well as a few other things).

**Comment by TruePhad** [comment]
You are right, I just did and indeed they are for the (\u0026).
Thank you for help!

**Comment by Cadehlinha** [comment]
You're welcome, and have a good day!

**Comment by ambr0sial** [comment]
whoops, sorry for the inconvenience, i hope the fork works well (and thank you @Cadehlinha!)
